'use client';

import React, { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { supabase } from '@/lib/supabase-client';
import { MarketEvent, formatTimeAgo, getTradingViewSymbol } from '@/components/FeedItem';
import TerminalErrorBoundary from '@/components/TerminalErrorBoundary';

export default function IntelDetailPage() {
  const params = useParams();
  const router = useRouter();
  const id = params.id as string;
  const [event, setEvent] = useState<MarketEvent | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchEvent() {
      try {
        const { data, error } = await supabase
          .from('events')
          .select('*')
          .eq('id', id)
          .single();

        if (!error && data) {
          setEvent({
            ...data,
            title: data.title || 'Untitled Event',
            source: data.source || 'Unknown Source',
            published_at: data.published_at || data.created_at || new Date().toISOString(),
            content: data.rationale || '',
            severity_score: data.severity_score || 0,
            bullish_assets: Array.isArray(data.bullish_assets) ? data.bullish_assets : [],
            bearish_assets: Array.isArray(data.bearish_assets) ? data.bearish_assets : [],
            ticker: getTradingViewSymbol(data.asset_class),
          } as MarketEvent);
        }
      } catch (err) {
        console.error('Failed to fetch event detail:', err);
      } finally {
        setLoading(false);
      }
    }
    fetchEvent();
  }, [id]);

  if (loading) {
    return (
      <div className="h-full w-full bg-slate-950 flex items-center justify-center font-mono text-xs text-slate-500 uppercase tracking-widest animate-pulse">
        Decrypting Intelligence...
      </div>
    );
  }

  if (!event) {
    return (
      <div className="h-full w-full bg-slate-950 flex flex-col items-center justify-center font-mono text-xs">
        <span className="text-red-500 uppercase tracking-widest mb-4">Event not found or classified</span>
        <button onClick={() => router.back()} className="text-slate-400 hover:text-white border border-slate-800 px-4 py-2 rounded-sm uppercase tracking-widest">
          Return to Feed
        </button>
      </div>
    );
  }

  return (
    <div className="h-full w-full bg-slate-950 overflow-y-auto font-mono text-xs leading-tight">
      <header className="h-12 border-b border-slate-800 bg-slate-900 flex items-center px-4 sticky top-0 z-10 shrink-0">
        <button onClick={() => router.back()} className="text-slate-400 hover:text-white font-bold tracking-widest uppercase flex items-center gap-2">
          <span>←</span> <span>BACK</span>
        </button>
      </header>

      <main className="p-4 md:p-8 max-w-3xl mx-auto flex flex-col gap-6">
        <TerminalErrorBoundary>
          <div className="border-b border-slate-800 pb-6">
            <h1 className="text-lg md:text-xl font-bold text-slate-100 mb-4 leading-snug">
              {event.title}
            </h1>
            <div className="flex flex-wrap items-center gap-4 text-[10px] text-slate-500 uppercase tracking-widest">
              <span>SOURCE: {event.source}</span>
              <span>TIME: {formatTimeAgo(event.published_at)}</span>
              <span className="text-red-400 border border-red-900/50 bg-red-950/20 px-2 py-0.5 rounded-sm font-bold">
                SEVERITY: {event.severity_score}/10
              </span>
              {event.url && (
                <a href={event.url} target="_blank" rel="noopener noreferrer" className="text-emerald-400 hover:underline">
                  [ORIGINAL SOURCE]
                </a>
              )}
            </div>
          </div>

          <div>
            <h2 className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-3 border-l-2 border-slate-700 pl-2">
              Executive Rationale
            </h2>
            <p className="text-sm text-slate-300 leading-relaxed bg-slate-900 border border-slate-800 p-4 rounded-sm">
              {event.rationale || 'No rationale generated by AI pipeline.'}
            </p>
          </div>

          <div className="flex flex-col gap-6">
            <div className="flex flex-col gap-2">
              <h2 className="text-[10px] font-bold text-slate-500 uppercase tracking-widest border-l-2 border-slate-700 pl-2">
                First Order Impact
              </h2>
              <p className="text-sm text-slate-300 leading-relaxed bg-slate-900 border border-slate-800 p-4 rounded-sm">
                {event.first_order_impact || 'Pending Analysis'}
              </p>
            </div>
            
            <div className="flex flex-col gap-2">
              <h2 className="text-[10px] font-bold text-slate-500 uppercase tracking-widest border-l-2 border-slate-700 pl-2">
                Second Order Effect
              </h2>
              <p className="text-sm text-slate-300 leading-relaxed bg-slate-900 border border-slate-800 p-4 rounded-sm">
                {event.second_order_effect || 'Pending Analysis'}
              </p>
            </div>
            
            <div className="flex flex-col gap-2">
              <h2 className="text-[10px] font-bold text-amber-500 uppercase tracking-widest border-l-2 border-amber-700 pl-2">
                Hidden Vulnerability
              </h2>
              <p className="text-sm text-amber-100 leading-relaxed bg-amber-950/20 border border-amber-900/50 p-4 rounded-sm font-bold">
                {event.hidden_vulnerability || 'Pending Analysis'}
              </p>
            </div>

            <div className="flex flex-col gap-2">
              <h2 className="text-[10px] font-bold text-slate-500 uppercase tracking-widest border-l-2 border-slate-700 pl-2">
                Confidence & Reasoning
              </h2>
              <p className="text-xs text-slate-400 italic leading-relaxed bg-slate-900/50 border border-slate-800/50 p-4 rounded-sm">
                {event.confidence_reasoning || 'Pending Analysis'}
              </p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4 opacity-80">
            <div className="flex flex-col border border-emerald-900/30 bg-emerald-950/5 p-3 rounded-sm">
              <span className="block text-[10px] font-bold text-emerald-500/70 mb-2 tracking-widest uppercase">
                ▲ Bullish Assets
              </span>
              <div className="flex flex-col gap-2">
                {event.bullish_assets && event.bullish_assets.length > 0 ? (
                  event.bullish_assets.map((asset, i) => {
                    const [ticker, ...reasoningParts] = asset.split(':');
                    return (
                      <div key={i} className="flex flex-col gap-0.5">
                        <span className="text-xs font-bold text-emerald-400/80">{ticker.trim()}</span>
                        <span className="text-[10px] text-emerald-500/60 leading-snug">{reasoningParts.join(':').trim()}</span>
                      </div>
                    );
                  })
                ) : (
                  <span className="text-[10px] text-emerald-900/50 uppercase tracking-widest">None Detected</span>
                )}
              </div>
            </div>

            <div className="flex flex-col border border-red-900/30 bg-red-950/5 p-3 rounded-sm">
              <span className="block text-[10px] font-bold text-red-500/70 mb-2 tracking-widest uppercase">
                ▼ Bearish Assets
              </span>
              <div className="flex flex-col gap-2">
                {event.bearish_assets && event.bearish_assets.length > 0 ? (
                  event.bearish_assets.map((asset, i) => {
                    const [ticker, ...reasoningParts] = asset.split(':');
                    return (
                      <div key={i} className="flex flex-col gap-0.5">
                        <span className="text-xs font-bold text-red-400/80">{ticker.trim()}</span>
                        <span className="text-[10px] text-red-500/60 leading-snug">{reasoningParts.join(':').trim()}</span>
                      </div>
                    );
                  })
                ) : (
                  <span className="text-[10px] text-red-900/50 uppercase tracking-widest">None Detected</span>
                )}
              </div>
            </div>
          </div>

          {event.url && (
            <div className="mt-8 flex justify-center border-t border-slate-800 pt-8">
              <a 
                href={event.url} 
                target="_blank" 
                rel="noopener noreferrer" 
                className="bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-600 px-6 py-3 rounded-sm text-xs font-bold tracking-widest uppercase transition-colors"
              >
                Read Full Article
              </a>
            </div>
          )}
        </TerminalErrorBoundary>
      </main>
    </div>
  );
}
